package com.lasertrac.main;
	
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Base64;
import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;

import org.hibernate.Session;
import org.ini4j.Ini;

import com.lasertrac.common.ConfigurationProps;
import com.lasertrac.common.IniFile;
import com.lasertrac.common.MyUtils;
import com.lasertrac.entity.HibernateUtil;
import com.lasertrac.entity.Test;
import com.lasertrac.settings.UsbRelay;
import com.lasertrac.tensor.TensorOcr;

import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.stage.Stage;
import javafx.util.Duration;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;


public class Main extends Application {
	@Override
	public void start(Stage primaryStage) {
		try {
			BorderPane root = new BorderPane();
			Scene scene = new Scene(root,400,400);
			scene.getStylesheets().add(getClass().getResource("/com/lasertrac/css/application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void main(String[] args) {
//		Session session = HibernateUtil.getSessionFactory().openSession(); 
//        session.beginTransaction();
// 
//        Test student = new Test();
// 
//        student.setUserName("JavaFun");
//        student.setPassword("19");
//
//        session.save(student);
////        try {
////            //Thread.sleep(20000);
////        } catch (InterruptedException e) {
////            // TODO Auto-generated catch block
////            e.printStackTrace();
////        }
// 
//        session.getTransaction().commit();
        
//		String str="0103020A";
//
//		System.out.println("Great! Student was saved");
//		System.out.println(str.substring(0, 2));
//		System.out.println(str.substring(2, 4));
//		System.out.println(str.substring(4, 6));
//		System.out.println(str.substring(6, 8));
		
		//ysb relay sample
//		UsbRelay.openRelay(UsbRelay.RelayOne);
//		try {
//			IniFile ini = new IniFile(ConfigurationProps.config_file);
//			int speed = ini.readIntValue(ConfigurationProps.IniSectionAndKeys.speedLimitSection, ConfigurationProps.IniSectionAndKeys.selectedSpeedIndex);
//			System.out.println(speed);
//		}catch(Exception ex) {
//			System.out.println(ex.toString());
//		}
		
//		try {
//			String cheeni = "/9j/4AAQSkZJRgABAgEASABIAAD/4QVxRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAUAAAAcgEyAAIAAAAUAAAAhodpAAQAAAABAAAAnAAAAMgAAABIAAAAAQAAAEgAAAABQWRvYmUgUGhvdG9zaG9wIDcuMAAyMDIwOjA1OjE0IDAwOjQ5OjMwAAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAEKgAwAEAAAAAQAAABIAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABFgEbAAUAAAABAAABHgEoAAMAAAABAAIAAAIBAAQAAAABAAABJgICAAQAAAABAAAEQwAAAAAAAABIAAAAAQAAAEgAAAAB/9j/4AAQSkZJRgABAgEASABIAAD/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIABIAQgMBIgACEQEDEQH/3QAEAAX/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/ALdmVXXZVW+d2S811wJEgF/u/shV7OqYWPj25NpcK6LfQfDZO8fut/OVbHtyOp4eF1PEp9R2NkPe+jcA4iHVHa/6O/3bkmdF6rkPZ6gZjMfbflWBwFoa60ejXSWAt3ubVvdvRCHRyuoUYbmG5xLLGb2hjS4hg+nc/b9Glu5L9qYoy2YpbaLLXbK3Gt2xxjf7LfoObt/OVI9K6w3EqZ6Iuu+x24D/AHgAAu/Q5Pu/M9P6bfprUxun3szvVuE1Y+PXj4pnvH6zZt/N3bWMTkIcnq+Ji32U2ttJoDXXPZWXMY1/0XWPb9FK/quLVc2iwWA2Oa2uz03Gslw3N22/Q+ihZuF1U5XUm42O2yvqFVdTbnWBoZDXV2OfX9N301Yd0q59zKnH9WxsM0Y7if8ACvHpWW7f5NQSUjp6zgux3Pc9xLAz/BuBf6h2Uuor+lY21/0E/wC0+nvOO0P/AEmU411VkEP3NkPD2fmbHN96pV9I6ofQyH0NbZgtxq2U+o39L6DnOtc1/wBFm/d+i3qzR0rLFeE6xrW2MzbMu9u4HY2z1IZu/P272IKSbfL/AA2z5JKr+1sX/SV/8o+j9IfR/wBIknUqw//Q4jB+g7+k8/8Aaf6PH538pWf/AHILmEk8Ken7/wDeir3Tf5q3+nfSb9P4H6K4pJOjug7Pd5f9Fs/pf0e3KxP/AGO+a59JKSA7x5/7WJj/AOhPzWEkgl0/81JZiSap/9n/7Qn+UGhvdG9zaG9wIDMuMAA4QklNBCUAAAAAABAAAAAAAAAAAAAAAAAAAAAAOEJJTQPtAAAAAAAQAEgAAAABAAEASAAAAAEAAThCSU0EJgAAAAAADgAAAAAAAAAAAAA/gAAAOEJJTQQNAAAAAAAEAAAAeDhCSU0EGQAAAAAABAAAAB44QklNA/MAAAAAAAkAAAAAAAAAAAEAOEJJTQQKAAAAAAABAAA4QklNJxAAAAAAAAoAAQAAAAAAAAACOEJJTQP1AAAAAABIAC9mZgABAGxmZgAGAAAAAAABAC9mZgABAKGZmgAGAAAAAAABADIAAAABAFoAAAAGAAAAAAABADUAAAABAC0AAAAGAAAAAAABOEJJTQP4AAAAAABwAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAADhCSU0ECAAAAAAAEAAAAAEAAAJAAAACQAAAAAA4QklNBB4AAAAAAAQAAAAAOEJJTQQaAAAAAANHAAAABgAAAAAAAAAAAAAAEgAAAEIAAAAJAHMAZQBsAGYAaQBtAGEAZwBlAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAABCAAAAEgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAAbnVsbAAAAAIAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAAAEgAAAABSZ2h0bG9uZwAAAEIAAAAGc2xpY2VzVmxMcwAAAAFPYmpjAAAAAQAAAAAABXNsaWNlAAAAEgAAAAdzbGljZUlEbG9uZwAAAAAAAAAHZ3JvdXBJRGxvbmcAAAAAAAAABm9yaWdpbmVudW0AAAAMRVNsaWNlT3JpZ2luAAAADWF1dG9HZW5lcmF0ZWQAAAAAVHlwZWVudW0AAAAKRVNsaWNlVHlwZQAAAABJbWcgAAAABmJvdW5kc09iamMAAAABAAAAAAAAUmN0MQAAAAQAAAAAVG9wIGxvbmcAAAAAAAAAAExlZnRsb25nAAAAAAAAAABCdG9tbG9uZwAAABIAAAAAUmdodGxvbmcAAABCAAAAA3VybFRFWFQAAAABAAAAAAAAbnVsbFRFWFQAAAABAAAAAAAATXNnZVRFWFQAAAABAAAAAAAGYWx0VGFnVEVYVAAAAAEAAAAAAA5jZWxsVGV4dElzSFRNTGJvb2wBAAAACGNlbGxUZXh0VEVYVAAAAAEAAAAAAAlob3J6QWxpZ25lbnVtAAAAD0VTbGljZUhvcnpBbGlnbgAAAAdkZWZhdWx0AAAACXZlcnRBbGlnbmVudW0AAAAPRVNsaWNlVmVydEFsaWduAAAAB2RlZmF1bHQAAAALYmdDb2xvclR5cGVlbnVtAAAAEUVTbGljZUJHQ29sb3JUeXBlAAAAAE5vbmUAAAAJdG9wT3V0c2V0bG9uZwAAAAAAAAAKbGVmdE91dHNldGxvbmcAAAAAAAAADGJvdHRvbU91dHNldGxvbmcAAAAAAAAAC3JpZ2h0T3V0c2V0bG9uZwAAAAAAOEJJTQQUAAAAAAAEAAAAAThCSU0EDAAAAAAEXwAAAAEAAABCAAAAEgAAAMgAAA4QAAAEQwAYAAH/2P/gABBKRklGAAECAQBIAEgAAP/tAAxBZG9iZV9DTQAB/+4ADkFkb2JlAGSAAAAAAf/bAIQADAgICAkIDAkJDBELCgsRFQ8MDA8VGBMTFRMTGBEMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAENCwsNDg0QDg4QFA4ODhQUDg4ODhQRDAwMDAwREQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM/8AAEQgAEgBCAwEiAAIRAQMRAf/dAAQABf/EAT8AAAEFAQEBAQEBAAAAAAAAAAMAAQIEBQYHCAkKCwEAAQUBAQEBAQEAAAAAAAAAAQACAwQFBgcICQoLEAABBAEDAgQCBQcGCAUDDDMBAAIRAwQhEjEFQVFhEyJxgTIGFJGhsUIjJBVSwWIzNHKC0UMHJZJT8OHxY3M1FqKygyZEk1RkRcKjdDYX0lXiZfKzhMPTdePzRieUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9jdHV2d3h5ent8fX5/cRAAICAQIEBAMEBQYHBwYFNQEAAhEDITESBEFRYXEiEwUygZEUobFCI8FS0fAzJGLhcoKSQ1MVY3M08SUGFqKygwcmNcLSRJNUoxdkRVU2dGXi8rOEw9N14/NGlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vYnN0dXZ3eHl6e3x//aAAwDAQACEQMRAD8At2ZVddlVb53ZLzXXAkSAX+7+yFXs6phY+Pbk2lwrot9B8Nk7x+6385Vse3I6nh4XU8Sn1HY2Q976NwDiIdUdr/o7/duSZ0XquQ9nqBmMx9t+VYHAWhrrR6NdJYC3e5tW929EIdHK6hRhuYbnEssZvaGNLiGD6dz9v0aW7kv2pijLZiltostdsrca3bHGN/st+g5u385Uj0rrDcSpnoi677HbgP8AeAAC79Dk+78z0/pt+mtTG6fezO9W4TVj49ePime8frNm383dtYxOQhyer4mLfZTa20mgNdc9lZcxjX/RdY9v0Ur+q4tVzaLBYDY5ra7PTcayXDc3bb9D6KFm4XVTldSbjY7bK+oVV1NudYGhkNdXY59f03fTVh3Srn3Mqcf1bGwzRjuJ/wAK8elZbt/k1BJSOnrOC7Hc9z3EsDP8G4F/qHZS6iv6VjbX/QT/ALT6e847Q/8ASZTjXVWQQ/c2Q8PZ+Zsc33qlX0jqh9DIfQ1tmC3GrZT6jf0voOc61zX/AEWb936LerNHSssV4TrGtbYzNsy727gdjbPUhm78/bvYgpJt8v8ADbPkkqv7Wxf9JX/yj6P0h9H/AEiSdSrD/9DiMH6Dv6Tz/wBp/o8fnfylZ/8AcguYSTwp6fv/AN6KvdN/mrf6d9Jv0/gforikk6O6Ds93l/0Wz+l/R7crE/8AY75rn0kpIDvHn/tYmP8A6E/NYSSCXT/zUlmJJqn/2QA4QklNBCEAAAAAAFUAAAABAQAAAA8AQQBkAG8AYgBlACAAUABoAG8AdABvAHMAaABvAHAAAAATAEEAZABvAGIAZQAgAFAAaABvAHQAbwBzAGgAbwBwACAANwAuADAAAAABADhCSU0EBgAAAAAABwAIAAAAAQEA/+ESSGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSfvu78nIGlkPSdXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQnPz4KPD9hZG9iZS14YXAtZmlsdGVycyBlc2M9IkNSIj8+Cjx4OnhhcG1ldGEgeG1sbnM6eD0nYWRvYmU6bnM6bWV0YS8nIHg6eGFwdGs9J1hNUCB0b29sa2l0IDIuOC4yLTMzLCBmcmFtZXdvcmsgMS41Jz4KPHJkZjpSREYgeG1sbnM6cmRmPSdodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjJyB4bWxuczppWD0naHR0cDovL25zLmFkb2JlLmNvbS9pWC8xLjAvJz4KCiA8cmRmOkRlc2NyaXB0aW9uIGFib3V0PSd1dWlkOmFhYzk4OGFiLTk1NGUtMTFlYS1hM2Q4LWVhNzhmNWYzODhhMycKICB4bWxuczp4YXBNTT0naHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyc+CiAgPHhhcE1NOkRvY3VtZW50SUQ+YWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjQyNGQwYmJiLTk1NGUtMTFlYS1hM2Q4LWVhNzhmNWYzODhhMzwveGFwTU06RG9jdW1lbnRJRD4KIDwvcmRmOkRlc2NyaXB0aW9uPgoKPC9yZGY6UkRGPgo8L3g6eGFwbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9J3cnPz7/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFjcHJ0AAABUAAAADNkZXNjAAABhAAAAGx3dHB0AAAB8AAAABRia3B0AAACBAAAABRyWFlaAAACGAAAABRnWFlaAAACLAAAABRiWFlaAAACQAAAABRkbW5kAAACVAAAAHBkbWRkAAACxAAAAIh2dWVkAAADTAAAAIZ2aWV3AAAD1AAAACRsdW1pAAAD+AAAABRtZWFzAAAEDAAAACR0ZWNoAAAEMAAAAAxyVFJDAAAEPAAACAxnVFJDAAAEPAAACAxiVFJDAAAEPAAACAx0ZXh0AAAAAENvcHlyaWdodCAoYykgMTk5OCBIZXdsZXR0LVBhY2thcmQgQ29tcGFueQAAZGVzYwAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z2Rlc2MAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZpZXcAAAAAABOk/gAUXy4AEM8UAAPtzAAEEwsAA1yeAAAAAVhZWiAAAAAAAEwJVgBQAAAAVx/nbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAo8AAAACc2lnIAAAAABDUlQgY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKQAqQCuALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLgAusC9QMAAwsDFgMhAy0DOANDA08DWgNmA3IDfgOKA5YDogOuA7oDxwPTA+AD7AP5BAYEEwQgBC0EOwRIBFUEYwRxBH4EjASaBKgEtgTEBNME4QTwBP4FDQUcBSsFOgVJBVgFZwV3BYYFlgWmBbUFxQXVBeUF9gYGBhYGJwY3BkgGWQZqBnsGjAadBq8GwAbRBuMG9QcHBxkHKwc9B08HYQd0B4YHmQesB78H0gflB/gICwgfCDIIRghaCG4IggiWCKoIvgjSCOcI+wkQCSUJOglPCWQJeQmPCaQJugnPCeUJ+woRCicKPQpUCmoKgQqYCq4KxQrcCvMLCwsiCzkLUQtpC4ALmAuwC8gL4Qv5DBIMKgxDDFwMdQyODKcMwAzZDPMNDQ0mDUANWg10DY4NqQ3DDd4N+A4TDi4OSQ5kDn8Omw62DtIO7g8JDyUPQQ9eD3oPlg+zD88P7BAJECYQQxBhEH4QmxC5ENcQ9RETETERTxFtEYwRqhHJEegSBxImEkUSZBKEEqMSwxLjEwMTIxNDE2MTgxOkE8UT5RQGFCcUSRRqFIsUrRTOFPAVEhU0FVYVeBWbFb0V4BYDFiYWSRZsFo8WshbWFvoXHRdBF2UXiReuF9IX9xgbGEAYZRiKGK8Y1Rj6GSAZRRlrGZEZtxndGgQaKhpRGncanhrFGuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMymzLUMw0zRjN/M7gz8TQrNGU0njTYNRM1TTWHNcI1/TY3NnI2rjbpNyQ3YDecN9c4FDhQOIw4yDkFOUI5fzm8Ofk6Njp0OrI67zstO2s7qjvoPCc8ZTykPOM9Ij1hPaE94D4gPmA+oD7gPyE/YT+iP+JAI0BkQKZA50EpQWpBrEHuQjBCckK1QvdDOkN9Q8BEA0RHRIpEzkUSRVVFmkXeRiJGZ0arRvBHNUd7R8BIBUhLSJFI10kdSWNJqUnwSjdKfUrESwxLU0uaS+JMKkxyTLpNAk1KTZNN3E4lTm5Ot08AT0lPk0/dUCdQcVC7UQZRUFGbUeZSMVJ8UsdTE1NfU6pT9lRCVI9U21UoVXVVwlYPVlxWqVb3V0RXklfgWC9YfVjLWRpZaVm4WgdaVlqmWvVbRVuVW+VcNVyGXNZdJ114XcleGl5sXr1fD19hX7NgBWBXYKpg/GFPYaJh9WJJYpxi8GNDY5dj62RAZJRk6WU9ZZJl52Y9ZpJm6Gc9Z5Nn6Wg/aJZo7GlDaZpp8WpIap9q92tPa6dr/2xXbK9tCG1gbbluEm5rbsRvHm94b9FwK3CGcOBxOnGVcfByS3KmcwFzXXO4dBR0cHTMdSh1hXXhdj52m3b4d1Z3s3gReG54zHkqeYl553pGeqV7BHtje8J8IXyBfOF9QX2hfgF+Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOutCW0nLUTtYq2AbZ5tvC3aLfguFm40blKucK6O7q1uy67p7whvJu9Fb2Pvgq+hL7/v3q/9cBwwOzBZ8Hjwl/C28NYw9TEUcTOxUvFyMZGxsPHQce/yD3IvMk6ybnKOMq3yzbLtsw1zLXNNc21zjbOts83z7jQOdC60TzRvtI/0sHTRNPG1EnUy9VO1dHWVdbY11zX4Nhk2OjZbNnx2nba+9uA3AXcit0Q3ZbeHN6i3ynfr+A24L3hROHM4lPi2+Nj4+vkc+T85YTmDeaW5x/nqegy6LzpRunQ6lvq5etw6/vshu0R7ZzuKO6070DvzPBY8OXxcvH/8ozzGfOn9DT0wvVQ9d72bfb794r4Gfio+Tj5x/pX+uf7d/wH/Jj9Kf26/kv+3P9t////7gAOQWRvYmUAZEAAAAAB/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgIDAwMDAwMDAwMDAQEBAQEBAQEBAQECAgECAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwP/wAARCAASAEIDAREAAhEBAxEB/90ABAAJ/8QBogAAAAYCAwEAAAAAAAAAAAAABwgGBQQJAwoCAQALAQAABgMBAQEAAAAAAAAAAAAGBQQDBwIIAQkACgsQAAIBAwQBAwMCAwMDAgYJdQECAwQRBRIGIQcTIgAIMRRBMiMVCVFCFmEkMxdScYEYYpElQ6Gx8CY0cgoZwdE1J+FTNoLxkqJEVHNFRjdHYyhVVlcassLS4vJkg3SThGWjs8PT4yk4ZvN1Kjk6SElKWFlaZ2hpanZ3eHl6hYaHiImKlJWWl5iZmqSlpqeoqaq0tba3uLm6xMXGx8jJytTV1tfY2drk5ebn6Onq9PX29/j5+hEAAgEDAgQEAwUEBAQGBgVtAQIDEQQhEgUxBgAiE0FRBzJhFHEIQoEjkRVSoWIWMwmxJMHRQ3LwF+GCNCWSUxhjRPGisiY1GVQ2RWQnCnODk0Z0wtLi8lVldVY3hIWjs8PT4/MpGpSktMTU5PSVpbXF1eX1KEdXZjh2hpamtsbW5vZnd4eXp7fH1+f3SFhoeIiYqLjI2Oj4OUlZaXmJmam5ydnp+So6SlpqeoqaqrrK2ur6/9oADAMBAAIRAxEAPwAwOc7RwW3c917tfPrXPle5N+Zzr3ZopqB6qllzWKwNfuGqjykySIuOo1xeOmYTEODJZbc39uQQI0IcxAsgqcj8qZrX18j/AIENyjtPRX7UUHjj/TfbUYxT06Cfcfyi6W632Bv/ALQ3hU52m2n1j23U9IbhNJt2qr8vLvzH1MENVSYXF083myeNp4agzvUKVC00UrkBUIJlBFQKqUoBxNAMn4fIV+fqePWpPGk0aSQcniDXHA8MfZ0LHZ3f+w+ka7bsu+c1V1GD3bs2femCodnbLz27MpidmYT7Go3H2ZuqswwqIsP1ziafL0iy1csarE7k3fkAwCW6nVIFVuArUkmnlilQeNemvptcjlS1afZT5tU+ZwBjAPWVfk51jB2xtfqKqxfaNLufe25ZNq7MzNR1RvCHYW769MQ2eat27vx6QYDK4RMMpqjWxyGnWGzMwBF6KqBXCyRkYwDRqmlBnFfkD+VOt+E4rIQxxxFKinE5OfTrP2T8u+qOqN7bz2Pu7GdpTy9aYbbG4+yt0bW6v3FuzZGwMDvClmrMJmN27mwwnjxGPNHTSSTymFhBHGzN6VJ9+SC3WSJC6h3UkCpIwT8qEYNc8emktv1G0y0qacRmvAH7Pl1y3v8AKrqvZ+88FsLcFJ2NS1W6M1gNvbT3nF1Vu/KdXZ3K7sxK5rCVOM37S038AyWNGKkNVUTRymOGnhlaQqsbEWAt2AKSxsTpBQE1BY0xihJJxWvpx68sLCM4NdJqTk1HE+ZHUTZvzL6NyGwc5nq/cG4a+p27TbJkkiTrDdWEzPY1N2Rm6rbXXed6n2nUwS5TeeC7Bz1HLT4yWkLLJIh1aEs3ttbWJ3kkikRo4wxJqdC6SAakgaj+EUHE48uqeGfHU6SzEimPUYBHlXiT5fn1mHya+P8AnajqPG0m5UfcfeO6spsrY2z6vA5Gj3iu5Nu1WZoNyUW5sDUxR1m1121lMFVUle1XbxVCBBq1A+3HggSKaUiNaOq0rnUTSgB4/M0otePT6QjV4a1/ioPIfb5g/b9vDqR9if8AlTi/5nZ/dL6yf8Af+VL/ADn/AAG/w9+8BP8AfS/F/L+H/V29LPCt/wCL/Qa/Cf2f7PDr/9AONg7o358rOnPi/wDKnpjrtN25Lp35Fb63Zn+pZd44TF53N4Obb+c2RX0WM3HVWwVFuGhjysVZFT1XijmiFg30JVOIbSYqpaSJuBVR50NdNRgcPXNadIZShuG8TGtCOFeNM4rio9OuOE+Fvyq7GzG2U3JSbM6i2/uHtf5KfJDetLn6Sg7fodv7r7fxsXXey+uq/AUWVwsO4Mrhdh1uRrp8jFKaSirZ1WLWyge3xcqfERbctHgDVVeHm2muk/Lh69U8WLQFEh1gAY4nNSeHD0/ydK2T4rfMLF9U9f4d+t8d2Bv0fDLuD4L7ikj3zgsVS4Omym8aP/Rt3TW1eTmIyG18hsuiR8pQwGTJU88aoI3uSFpuRRGeJjp1UotasR5nBA+fCmfLqjTQFZHLRmNip885yOGD6eny6Pn1p0BvbBd3ruzesCVuz+ovjn1P0V0XXNkI6hZq44sP3bu6PDk+XCV+ZrsPi8ckjhZZaGAqp0FgW1ld/p0MVIlBYjiPEIoSONaDCmmD+dGHmjkWV0GWkr5/CBQfL5k4FQOi7d0dL/KmftH5p0HVfTm3dz7X+WXWPV3WmB7J3F2bgtuYbYMWI2Jn9mbuzG5NpPBV7kziY6Dccs9NDSqv3EkSqSFYn3b6tImibwXebQVHaCCamhLHgBqBpSpzQdaWVBEiSSgUkJqVOQSMjHHFBWnQy1vxW3ZmN3bX2rlKmNuqOmPhrkuleoc5VZOOaabuLfu3anYG8d91mCjlaWiqcFsjGUtPR1JF1iyFSkbX1E2hdkG31XtjfWxoQrOKBQcZ0jUQT+Ig9baQ6bt4sF2ytcAA1OfmaVHy8+ieYL4i/KCtl6s7JzfV2Dw26fjBtb4d7F2t1nD2Xtepn7lp/jpuzcub39ncJuCKVcNtugz9JmojgYsmY5jURv8AcCIEH2nIOhLcLMLdEYFgtas0gcgKDkADjUVNadKBcRK0oZ1KM5IzQKCumla+p4A4/l0Ouyfit2tQ7b+M2R3Ph9sYvcmC+b/avyn7ZxKbpwta2xdsdi03ZNTjttUeaVlh3JkcJPuOghqxTMYHnaV0LIuo7uGFwl9IkL+LLcIVJUVCgjiRUhiFBIFc+tOqGa3iorutEgKjIyflxxk1r8ug2/2bHq3/AJ7HYH/byL/RB/x+WI/4sX/PWf5//gB/tX+a/wCbvsS+BH/vzy08F+L04/8AGePSXx0/g/0L+Ly/3nh8uHz6/9HVw6P/AOLPnf8Aspn/AIu4/wCZA/8AHr/8Ak/4vP8A1fP+uVvZ/bf7jTf2n9of7Ph5cOm7j8P9n+L7OP8Aqp0NK/j/ALeLfqH+a/V9R+n/AA/r/j7Mv9Gm/teA4/Yf9R6Tjg39n8B4fl/q/Z1gT/OR/wDbyT/PL/nP0/qH6v8Aav6f7V7uP7cf7lcR8P8Al+X+SvXo/ik/sfhHD/J/q4dGs+OX/Ht9gf8AZdH/ABfdr/8AH6f8CP8Ai2Zb/i2/9M//AB2/5u6PZvsP9tP8XwL/AGvw8fLpLc/7ht/Y/Efg+H4Tx/1evQl9t/8AMr95/wDZWv8AxYp/+Lb/AMXP/O/8on/TV/X/AGn2pv8A4Z/g+E/D/k+fRdbf2y/2XAfF9o4f5OqtH/S3/ZdX/VT/AJ79Cfr/ANo/p/tVvYZH9hL/ALk8PP4Py/1cejheI/3F+I/5eP8Az98+m2s/zn/c5P6W/wA99Pov1/5uf197H9n/AMSuA+zj59NRf2a/7j/5P+L/AMvTbVfpf/sqH6f8vH/M/oH+d/5s/wDHT/aPdrb+0H+5Xw/h4cf9VOnF4R/2PHz+D8/l/lp0B/8A6Dv6v99/099l3/OT4f8AV/zc6t/vPw/6v+bfX//Z";
//	        
//			TensorOcr to=new TensorOcr();
//			cheeni = encodeToString(ImageIO.read(new File("C:\\Users\\LaserTrac\\Desktop\\custom\\n1\\n5.jpg")) , "JPG");
//			
//			String str = to.getOcr(cheeni);
//			System.out.println("output = " + str);
//			
//			//#2
//			System.out.println("myocr start time="+MyUtils.logTimeFormatter.format(new Date()));
//			
//			cheeni = encodeToString(ImageIO.read(new File("C:\\Users\\LaserTrac\\Desktop\\custom\\n1\\n6.jpg")) , "JPG");
//			String str1 = to.getOcr(cheeni);
//			System.out.println("output = " + str1);
//			
//			System.out.println("myocr start time="+MyUtils.logTimeFormatter.format(new Date()));
//			
//			System.out.println("-------------");
//			//#3
//			System.out.println("myocr start time="+MyUtils.logTimeFormatter.format(new Date()));
//			
//			cheeni = encodeToString(ImageIO.read(new File("C:\\Users\\LaserTrac\\Desktop\\custom\\n1\\np(1).jpg")) , "JPG");
//			str1 = to.getOcr(cheeni);
//			System.out.println("output = " + str1);
//			
//			System.out.println("myocr start time="+MyUtils.logTimeFormatter.format(new Date()));
//			
//		}catch(Exception ex) {
//			System.out.println("error = "+ex.getMessage());
//		}
		//startAutoEvidence();
		checkExecutors();
		launch(args);
	}
	
	static int count=0;
	private static final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
	static void checkExecutors() {
		final Runnable beeper = new Runnable() {
	            public void run() { 
	            	int mcount= count;
	            	System.out.println(mcount+" beep "+MyUtils.logTimeFormatter.format(new Date()).toString()); 
	            	try {
	            		Thread.sleep(300);	
	            	}catch(Exception ex) {
	            		
	            	}
	            	System.out.println(mcount+" beep ends "+MyUtils.logTimeFormatter.format(new Date()).toString()); 
	            	
	            	count+=1;
	            }
	    };
	    final ScheduledFuture<?> beeperHandle = scheduler.scheduleAtFixedRate(beeper, 100, 200, TimeUnit.MILLISECONDS);

	    //stop schedule 
	    //scheduler.schedule(new Runnable() {
	    	//public void run() { beeperHandle.cancel(true); }
	    //}, 1000, TimeUnit.MILLISECONDS);
		
	}
	
	static void startAutoEvidence() {
		Timeline fiveSecondsWonder = new Timeline(new KeyFrame(Duration.millis(200), new EventHandler<ActionEvent>() {
    		int count=0;
    	    @Override
    	    public void handle(ActionEvent event) {
    	    	System.out.println(count+" hello world = "+MyUtils.logTimeFormatter.format(new Date()).toString());
//    	    	Runnable r = new Runnable() {
//    				public void run() {
//    					processImage();
//    				}
//    			};
//    	 
//    			Thread t = new Thread(r);
//    			t.start();
    	    	try {
    	    		Thread.sleep(400);	
    	    	}catch(Exception ex) {
    	    		
    	    	}
    	    	
    	    	
    	    	System.out.println(count+" hello world ends = "+MyUtils.logTimeFormatter.format(new Date()).toString());
    	    		
    	    	count += 1;
    	    	
    	    	
    	    }
    	}));
    	fiveSecondsWonder.setCycleCount(Timeline.INDEFINITE);
    	fiveSecondsWonder.play();
		
	}
	
	public static String encodeToString(BufferedImage image, String type) {
	    String imageString = "";
	    ByteArrayOutputStream bos = new ByteArrayOutputStream();

	    try {
	        ImageIO.write(image, type, bos);
	        byte[] imageBytes = bos.toByteArray();

	        Base64.Encoder encoder = Base64.getEncoder();
	        imageString = encoder.encodeToString(imageBytes);

	        bos.close();
	    } catch (IOException e) {
	        e.printStackTrace();
	    }
	    return imageString;
	}
	
}
